### ISSUE TITLE
Specify ignore/black list

### ISSUE THREAD

**Issue by alexlopespereira** [lpinner/metageta#52]
I would like to specify a set of keywords that when metageta finds it in the filepath it will not add the corresponding image to destination shapefile.

Is it easy to do that?

Thank you,
Alex

**Comment by alexlopespereira** [comment]
I saw the code and I guess I could put some verification in this part of the __runcrawler__.py file.

 #Loop thru dataset objects returned by Crawler
        for ds in Crawler:
            try:
                logger.debug('Attempting to open %s'%Crawler.file)
                fi=ds.fileinfo
                fi['filepath']=utilities.uncpath(fi['filepath'])
                #Check whether the file path containg any keywords from the blacklist
                #if it does, then step to the next file (next loop iteration)
                #Questions: It would be rather inefficient when I specify a directory name as a keyword, which is my goal.
                #Any suggestion about how to do that?

**Comment by lpinner** [comment]
@alexlopespereira are  you wanting to exclude entire directories, filenames or both? Do you wish to exclude partial file/directory string matches?

**Comment by alexlopespereira** [comment]
I would like to exclude entire directories and files with a given extension such as jpg and png. 
A generic solution with an expression such as "LIKE %keyword%" would be good because it is generic and would fulfill any user request.
Would you suggest any approach? Could you point the part of the could that would be suitable to implement this feature?

Thanks.

**Comment by lpinner** [comment]
@alexlopespereira try the [develop](https://github.com/lpinner/metageta/tree/develop) branch. I've implemented simple file/dir exclusions.

**Comment by alexlopespereira** [comment]
@lpinner that is perfect and excellent. Now I can use the error log as a burndown/to-do list of my image repository folder.
I would just suggest to explain in the parameter help the syntax is a space quoted list or put an example. It might not be straightforward that the correct syntax. For example, I also tried -e '*.jpg','*temporary*','*.bmp' and another trial -e '*.jpg' -e '*temporary*' -e '*.bmp'.
Thank you very much.

**Comment by lpinner** [comment]
Parameter help updated to 'Space delimited glob style file/directory basename exclusion pattern/s i.e *.png somedir? img_[0-9][0-9].tif'
